name: Release
on:
  push:
    tags:
      - v*

jobs:
  release-binaries:
    name: Release binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.22"
      - name: Read version from main.go
        id: get-version
        run: |
          VERSION=$(grep 'var version = ' main.go | cut -d '"' -f2)
          echo "Version: $VERSION"
          echo "::set-output name=version::$VERSION"
      - name: Build binaries
        run: |
          go build -o sshesame-linux-amd64
          env:
            GOOS: linux
            GOARCH: amd64
      - name: Build for other platforms
        run: |
          go build -o sshesame-linux-armv6
          env:
            GOOS: linux
            GOARCH: arm
            GOARM: 6
          go build -o sshesame-linux-armv7
          env:
            GOOS: linux
            GOARCH: arm
            GOARM: 7
          go build -o sshesame-linux-arm64
          env:
            GOOS: linux
            GOARCH: arm64
          go build -o sshesame-macos-amd64
          env:
            GOOS: darwin
            GOARCH: amd64
          go build -o sshesame-macos-arm64
          env:
            GOOS: darwin
            GOARCH: arm64
          go build -o sshesame-windows-amd64.exe
          env:
            GOOS: windows
            GOARCH: amd64
          go build -o sshesame-windows-armv7.exe
          env:
            GOOS: windows
            GOARCH: arm
            GOARM: 7
          go build -o sshesame-windows-arm64.exe
          env:
            GOOS: windows
            GOARCH: arm64
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: "sshesame-pro v${{ steps.get-version.outputs.version }}"
          files: |
            sshesame-linux-amd64
            sshesame-linux-armv6
            sshesame-linux-armv7
            sshesame-linux-arm64
            sshesame-macos-amd64
            sshesame-macos-arm64
            sshesame-windows-amd64.exe
            sshesame-windows-armv7.exe
            sshesame-windows-arm64.exe